fn main() {
    let now = jiff::Zoned::now();
    let date = now.strftime("%Y-%m-%d %H:%M:%S %z").to_string();
    println!("cargo:rustc-env=BUILD_DATE={}", date);

    // Command registration: scan src/cmd/ for command module files
    generate_cmd_mods().expect("failed to generate cmd_mods.rs");
}

/// Auto-discover command modules in src/cmd/ and generate mod declarations.
///
/// Scans `src/cmd/*.rs`, excluding `mod.rs`, and writes a generated
/// file to `src/cmd/__cmd_reg__.rs` with `mod xxx;` lines.
/// Adding a new command = drop a file in `src/cmd/`, no manual registration.
///
/// The file is included via `include!` from `cmd/mod.rs`, so the `mod`
/// declarations inside it resolve to `src/cmd/xxx.rs` correctly.
fn generate_cmd_mods() -> std::io::Result<()> {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let cmd_dir = std::path::Path::new(&manifest_dir).join("src/cmd");

    let mut mods: Vec<String> = Vec::new();
    if cmd_dir.is_dir() {
        for entry in std::fs::read_dir(&cmd_dir)? {
            let entry = entry?;
            let path = entry.path();
            if path.extension().map_or(true, |e| e != "rs") {
                continue;
            }
            let stem = path.file_stem().unwrap().to_string_lossy();
            // Skip mod.rs and any generated file
            if stem == "mod" || stem.starts_with("__") {
                continue;
            }
            mods.push(stem.to_string());
        }
    }

    mods.sort();

    let mut output = String::from("// Auto-generated by build.rs — do not edit manually.\n");
    output.push_str("// Add a .rs file to src/cmd/ to register a new command.\n\n");
    for m in &mods {
        output.push_str(&format!("pub(crate) mod {m};\n"));
    }

    let dest = cmd_dir.join("__cmd_reg__.rs");
    std::fs::write(&dest, output)?;

    println!("cargo:rerun-if-changed=src/cmd/");
    Ok(())
}
