//! CLI command dispatch and argument parsing.
//!
//! Defines the top-level [`Cli`] struct and [`Command`] enum via `clap`,
//! and the [`start()`] entry point that drives the whole binary.
//!
//! # Design
//!
//! - **Auto-discovered commands**: `build.rs` scans `src/cmd/` for `.rs`
//!   files and generates `__cmd_reg__.rs` (included below). Adding a new
//!   command is as simple as dropping a file into that directory — no
//!   manual registration needed.
//! - **i18n before parse**: Language is detected from CLI args *before*
//!   `Cli::parse()` so that help text appears in the correct language.
//!   The [`I18nHelp`] derive macro patches the clap command tree.
//! - **Config-driven initialisation**: After parsing, session config is
//!   read to apply `output_style`, `language`, and `no_color` — the CLI
//!   `--lang` / `--no-color` flags take precedence over config values.
//! - **Double-pass language init**: First pass detects `--lang` from raw
//!   args for help text; second pass (after parse) re-initialises if the
//!   user explicitly chose a language or the config specifies one.
//!
//! # Adding a new command
//!
//! 1. Create `src/cmd/<name>.rs` with a public `execute()` function.
//! 2. Add a variant to the [`Command`] enum in this file.
//! 3. Add the match arm in the `start()` dispatch block.
//!    (Build-time command registration is separate — see `build.rs`.)
//!
//! # Important Notes
//!
//! - Logger init (`setup_logger`) must happen after `i18n::init_language()`
//!   because log output may need translated strings.
//! - `HOK_LOG_LEVEL` env var overrides the log level for `libscoop` only;
//!   other crates use `RUST_LOG` or the default filter.

use clap::{crate_description, crate_name, crate_version, CommandFactory, FromArgMatches, Parser, Subcommand};
use clap_verbosity_flag::Verbosity;
use hok_i18n_derive::I18nHelp;
use libscoop::Session;
use rust_i18n::t;
use tracing_subscriber::{
    filter::LevelFilter, layer::SubscriberExt, util::SubscriberInitExt, EnvFilter,
};

use crate::i18n::{self, LanguageChoice};

// Auto-discovered command modules (generated by build.rs)
// Add a .rs file to src/cmd/ to register a new command — no manual edits needed.
include!("__cmd_reg__.rs");

use crate::Result;

#[derive(Parser)]
#[derive(I18nHelp)]
#[command(
    name = crate_name!(),
    version = format!("{} (built {})", crate_version!(), option_env!("BUILD_DATE").unwrap_or("unknown")),
    about = crate_description!(),
    long_about = format!("{}

If you find any bugs or have a feature request, please open an issue on
GitHub: https://github.com/chawyehsu/hok/issues", crate_description!()),
    subcommand_required = true,
    arg_required_else_help = true,
    max_term_width = 100,
    after_help = format!(
        "Type '{} help <command>' to get help for a specific command.",
        crate_name!()
    )
)]
pub struct Cli {
    #[command(subcommand)]
    pub command: Command,

    /// The verbosity level
    #[command(flatten)]
    verbose: Verbosity,

    /// Show detailed operation information for debugging
    #[arg(global = true, long)]
    pub detail: bool,

    /// Force CLI language (auto/en/zh)
    #[arg(global = true, long = "lang", short = 'L', default_value_t = LanguageChoice::Auto, value_enum)]
    pub language: LanguageChoice,

    /// Disable colored output
    #[arg(global = true, long = "no-color", short = 'N')]
    pub no_color: bool,
}

#[derive(Subcommand)]
pub enum Command {
    Alias(alias::Args),
    /// CI auto-pr: auto-update manifests and create PRs via GitHub API
    #[clap(name = "ci-auto-pr")]
    CiAutoPr(auto_pr::Args),
    Bucket(bucket::Args),
    Cache(cache::Args),
    Cat(cat::Args),
    Checkhashes(checkhashes::Args),
    Checkup(checkup::Args),
    Checkurls(checkurls::Args),
    Checkver(checkver::Args),
    Cleanup(cleanup::Args),
    Completions(completions::Args),
    Config(config::Args),
    Create(create::Args),
    Depends(depends::Args),
    Export(export::Args),
    FormatJson(formatjson::Args),
    Hold(hold::Args),
    Home(home::Args),
    Import(import::Args),
    Info(info::Args),
    Install(install::Args),
    List(list::Args),
    MissingCheckver(missing_checkver::Args),
    Prefix(prefix::Args),
    Reinstall(reinstall::Args),
    #[clap(alias = "s")]
    Search(search::Args),
    Shim(shim::Args),
    Status(status::Args),
    Reset(reset::Args),
    Unhold(unhold::Args),
    #[clap(alias = "rm", alias = "remove")]
    Uninstall(uninstall::Args),
    #[clap(alias = "u")]
    Update(update::Args),
    Upgrade(upgrade::Args),
    Virustotal(virustotal::Args),
    Which(which::Args),
}

/// CLI entry point
pub fn start() -> Result<()> {
    // Detect language before Cli::parse() so help text is rendered in the right language
    let preselected_language = i18n::detect_language_choice_from_args();
    i18n::init_language(preselected_language);

    let args = {
        let cmd = Cli::patch_i18n(Cli::command());
        Cli::from_arg_matches(&cmd.get_matches())
    }?;

    // If user explicitly set --lang in Cli args (not auto), re-init with explicit choice
    if !matches!(args.language, LanguageChoice::Auto) {
        i18n::init_language(args.language);
    }

    setup_logger(args.verbose.tracing_level_filter(), args.detail)?;
    crate::set_detail(args.detail);

    let session = Session::default();
    let user_agent = format!("Scoop/1.0 (+https://scoop.sh/) Hok/{}", crate_version!());
    let _ = session.set_user_agent(&user_agent);

    // --- Config-driven initialization ---
    let config = session.config();

    // Set output style from config (default: scoop)
    crate::output::set_style(config.output_style());

    // Apply language from config if --lang was not explicitly set
    if matches!(args.language, LanguageChoice::Auto) {
        let cfg_lang = config.language();
        if cfg_lang != "auto" {
            let choice = match cfg_lang.to_lowercase().as_str() {
                "en" => LanguageChoice::En,
                "zh" => LanguageChoice::Zh,
                _ => LanguageChoice::Auto,
            };
            i18n::init_language(choice);
        }
    }

    // Color setting: CLI --no-color > config no_color > default enabled
    let no_color = args.no_color || config.no_color();
    crate::output::set_color_enabled(!no_color);

    drop(config);

    match args.command {
        Command::Alias(args) => alias::execute(args, &session),
        Command::CiAutoPr(args) => auto_pr::execute(args, &session),
        Command::Bucket(args) => bucket::execute(args, &session),
        Command::Cache(args) => cache::execute(args, &session),
        Command::Cat(args) => cat::execute(args, &session),
        Command::Checkhashes(args) => checkhashes::execute(args, &session),
        Command::Checkup(args) => checkup::execute(args, &session),
        Command::Checkurls(args) => checkurls::execute(args, &session),
        Command::Checkver(args) => checkver::execute(args, &session),
        Command::Cleanup(args) => cleanup::execute(args, &session),
        Command::Completions(args) => completions::execute(args),
        Command::Config(args) => config::execute(args, &session),
        Command::Create(args) => create::execute(args, &session),
        Command::Depends(args) => depends::execute(args, &session),
        Command::Export(args) => export::execute(args, &session),
        Command::FormatJson(args) => formatjson::execute(args),
        Command::Hold(args) => hold::execute(args, &session),
        Command::Home(args) => home::execute(args, &session),
        Command::Import(args) => import::execute(args, &session),
        Command::Info(args) => info::execute(args, &session),
        Command::Install(args) => install::execute(args, &session),
        Command::List(args) => list::execute(args, &session),
        Command::MissingCheckver(args) => missing_checkver::execute(args),
        Command::Prefix(args) => prefix::execute(args, &session),
        Command::Reinstall(args) => reinstall::execute(args, &session),
        Command::Search(args) => search::execute(args, &session),
        Command::Shim(args) => shim::execute(args, &session),
        Command::Reset(args) => reset::execute(args, &session),
        Command::Status(args) => status::execute(args, &session),
        Command::Unhold(args) => unhold::execute(args, &session),
        Command::Uninstall(args) => uninstall::execute(args, &session),
        Command::Update(args) => update::execute(args, &session),
        Command::Upgrade(args) => upgrade::execute(args, &session),
        Command::Virustotal(args) => virustotal::execute(args, &session),
        Command::Which(args) => which::execute(args, &session),
    }
}

fn setup_logger(level_filter: LevelFilter, detail: bool) -> Result<()> {
    // When --detail is active, ensure at least DEBUG level (unless user set higher via -vv)
    let effective_level = if detail { level_filter.max(LevelFilter::DEBUG) } else { level_filter };

    // filter for low-level/depedency logs
    let low_level_filter = match effective_level {
        LevelFilter::OFF => LevelFilter::OFF,
        LevelFilter::ERROR => LevelFilter::ERROR,
        LevelFilter::WARN => LevelFilter::WARN,
        LevelFilter::INFO => LevelFilter::WARN,
        LevelFilter::DEBUG => LevelFilter::INFO,
        LevelFilter::TRACE => LevelFilter::TRACE,
    };

    let mut layer_env_filter = EnvFilter::builder()
        .with_default_directive(effective_level.into())
        .from_env()?;

    // The custom `HOK_LOG_LEVEL` environment variable was introduced to set the
    // log level for hok since the first version.
    if let Ok(level) = std::env::var("HOK_LOG_LEVEL") {
        layer_env_filter = layer_env_filter.add_directive(format!("libscoop={level}").parse()?);
    }

    layer_env_filter = layer_env_filter
        // add low-level filter for git2
        .add_directive(format!("git2={}", low_level_filter).parse()?)
        // shortcuts-rs uses log crate internally; suppress its verbose debug output
        .add_directive("shortcuts_rs=warn".parse()?);

    let layer_fmt = tracing_subscriber::fmt::layer().without_time();

    tracing_subscriber::registry()
        .with(layer_env_filter)
        .with(layer_fmt)
        .init();

    Ok(())
}
